flipkart/urls.py
from django.urls import path
from flipkart.views import *

app_name='flipkart'

urlpatterns=[
    path('samsungtab/',samsungtab,name='samsungtab'),
    path('realmetab/',realmetab,name='realmetab'),
    
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import flipkart
from amazon.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ipad/',ipad,name='ipad'),
    path('mitab/',mitab,name='mitab'),
    path('flipkart/',include('flipkart.urls')),
]

amazon/models.py
from django.db import models

# Create your models here.

flipkart/models.py
from django.db import models

# Create your models here.

amazon/views.py
from django.shortcuts import render

# Create your views here.
def ipad(request):
    p={'model': 'Ipad Air (2023)', 'cost':'60,000'}
    return render(request,'ipad.html',p)

def mitab(request):
    q={'model': 'Mi Tab', 'cost':'25,000'}
    return render(request,'mitab.html',q)

flipkart/views.py
from django.shortcuts import render

# Create your views here.

def samsungtab(request):
    m={'model': 'SAMSUNG GALAXY TAB S7FE', 'cost':'45,000'}
    return render(request,'samsungtab.html',m)

def realmetab(request):
    q={'model': 'REALME PAD (2023)', 'cost':'17,000'}
    return render(request,'realmetab.html',q)

templates/ipad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Amazon</title>
</head>
<body>
    <center>
        <h1>MODEL : {{model}}</h1>
        <h1>COST : {{cost}}</h1>
        <a href="{% url 'mitab' %}">go to mi tab - amazon page</a>
    </center>
</body>
</html>

templates/mitab.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Amazon</title>
</head>
<body>
    <center>
        <h1>MODEL : {{model}}</h1>
        <h1>COST : {{cost}}</h1>
        <a href="{% url 'ipad' %}">go to ipad - amazon page</a>
    </center>
</body>
</html>

templates/realmetab.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flipkart</title>
</head>
<body>
    <center>
        <h1>MODEL : {{model}}</h1>
        <h1>COST : {{cost}}</h1>
        <a href="{% url 'flipkart:samsungtab' %}">go to realmetab - flipkart page</a>
    </center>
</body>
</html>

templates/samsungtab.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flipkart</title>
</head>
<body>
    <center>
        <h1>MODEL : {{model}}</h1>
        <h1>COST : {{cost}}</h1>
        <a href="{% url 'flipkart:realmetab' %}">go to realmetab - flipkart page</a>
    </center>
</body>
</html>